# 9 Cálculos Matriciales

In [11]:
import numpy as np

In [12]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#Suma
sum = A + B
print(A)
print(B)
print(sum)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [13]:
#Multiplicación
product = np.dot(A, B)
print(product)

[[19 22]
 [43 50]]


In [14]:
A = np.array([[1,2],[3,4]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(A)
print(det_A)
print(inv_A)

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
#Resolver Ax = b
b = np.array([9,11])
x = np.linalg.solve(A,b)
print(x)

[-7.  8.]
