Clase uno de  data cience with python

In [1]:
print('hola mundo')

hola mundo


In [ ]:
import  numpy as  np 

escalar  = np.array(42)
print(type(escalar))
print(escalar)

vector = np.array([39,42,31,33,35,36,38,49])
print(type(vector))
print(vector)

matriz = np.array([[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])
print(type(matriz))
print(matriz)

tensor = np.array([[[1,2,3], 
                   [4,5,6], 
                   [7,8,9]])

print(type(tensor))
print(tensor)


<class 'numpy.ndarray'>
42
<class 'numpy.ndarray'>
[39 42 31 33 35 36 38 49]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [19]:
array_arange = np.arange(54)
print(array_arange)

matrix_eye= np.eye(6)
print(matrix_eye)

diag_matrix = np.diag([1,2,3,4,5,6])
print(diag_matrix)

random_matrix = np.random.random((7,5))
print(random_matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
[[0.07791593 0.16433432 0.93236892 0.93734886 0.68909874]
 [0.88786324 0.08192919 0.1470859  0.08429675 0.40599094]
 [0.09452414 0.09171835 0.60604165 0.12994853 0.49045235]
 [0.19446829 0.92559315 0.90734539 0.89186146 0.07513121]
 [0.07551691 0.84844325 0.82462561 0.10095495 0.95624823]
 [0.31066816 0.28475713 0.7978828  0.13344013 0.00907811]
 [0.24888665 0.59020038 0.82063198 0.21082706 0.06595891]]


In [27]:
#tarea otros metodos 
print(np.zeros((3, 4)))  # Matriz 3x4 de ceros)
print(np.ones((2, 3)))  # Matriz 2x3 de unos)
print(np.empty((3, 3)))  # Matriz 3x3 sin inicializar)
print(np.linspace(0, 10, 5)) # [ 0.   2.5  5.   7.5 10. ]  Crea un array con valores espaciados uniformemente entre dos números:
print(np.random.randn(3, 3)) # Matriz 3x3 con distribución normal estándar
print(np.random.randint(1, 10, (3, 3)))  # Matriz 3x3 con enteros entre 1 y 9

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-0.13871528  2.14694784  0.63453993]
 [ 0.61898149 -0.90094654  1.38107237]
 [ 0.69673183 -1.4175785   1.49485203]]
[ 0.   2.5  5.   7.5 10. ]
[[ 0.57805389 -0.73074227  0.00567503]
 [ 1.18649397  1.35778547  0.49597766]
 [ 1.32899048  0.16486532  0.97842956]]
[[3 2 8]
 [1 3 1]
 [1 5 2]]
