In [3]:
import numpy as np 


In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

suma = A + B
print("Suma de matrices:\n", suma)


Suma de matrices:
 [[ 6  8]
 [10 12]]


In [5]:
producto = np.dot(A, B)
print("Producto de matrices:\n", producto)


Producto de matrices:
 [[19 22]
 [43 50]]


In [8]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

A_transpuesta = A.T  # Transponer la matriz
print(A_transpuesta)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
A = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7,8, 9]])
determinante = np.linalg.det(A)
print("Determinante de A:", determinante)


inversa = np.linalg.inv(A)
print("Inversa de A:\n", inversa)

valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

B = np.array([1, 2,3])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)

Determinante de A: -9.51619735392994e-16
Inversa de A:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Valores propios de A:
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Vectores propios de A:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
Solución del sistema AX = B:
 [-0.23333333  0.46666667  0.1       ]
