In [2]:
import numpy as np 

In [3]:

# slicing
array = np.array([1,2,3,4,5,6,7])
print(array[1])
print(array[0])
print(array[1:4])
print(array[1:11])
print(array[-1:-11])
# indexacion booleana
bool_index = array >= 4
print(bool_index)
# acceder mediante indices
a_index = [2,4,0]
print(array[a_index])



#slicing con matrices
matriz = np.random.randint(1,11,size=(3,3))
print(matriz)
print(matriz[1,0])

print(matriz[:1,:2])


2
1
[2 3 4]
[2 3 4 5 6 7]
[]
[False False False  True  True  True  True]
[3 5 1]
[[5 9 8]
 [5 9 7]
 [3 5 8]]
5
[[5 9]]


In [4]:
#broadcasting con numpy
prices = np.random.randint(100,300,(3,3))
discount = np.array([0.25])
discounted_prices = prices * discount
print(prices)
print(discounted_prices ) 

print(prices - discounted_prices) 

#operaciones logicas

print(np.all(prices > 0))
print(np.all(prices < 0))
print(np.all(prices < 500))
print(np.all(prices < 100))


#concatenacion


#matrices
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
B = np.array([[7, 8, 9]])             # Shape (1, 3)

C = np.concatenate((A, B), axis=0)  # Une por filas (verticalmente)
print(C) 

D = np.array([[10], [20]])  # Shape (2,1)

E = np.concatenate((A, D), axis=1)  # Une por columnas (horizontalmente)
print(E)

F = np.concatenate((A,B), axis=0)
print(F)
#vstaking

#np.concatenate((A, D), axis=1)

#✔ np.vstack((A, B)) → Une verticalmente (equivalente a axis=0).
#✔ np.hstack((A, B)) → Une horizontalmente (equivalente a axis=1).
#✔ np.dstack((A, B)) → Une en el tercer eje (útil para imágenes).
V = np.vstack((A, B))
H = np.hstack((A, D)) 
print( A)
print( B)
print( V)
print(H)



[[105 135 259]
 [268 140 146]
 [262 232 163]]
[[26.25 33.75 64.75]
 [67.   35.   36.5 ]
 [65.5  58.   40.75]]
[[ 78.75 101.25 194.25]
 [201.   105.   109.5 ]
 [196.5  174.   122.25]]
True
False
True
False
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 20]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 20]]


In [5]:
array_c = np.arange(1,10)
split_array = np.split(array_c,1)
print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3, 4, 5, 6, 7, 8, 9])]


In [6]:
survey_responses = np.array(["bueno", "excelente", "malo", "bueno", "bueno", "malo", "malo", "bueno", "excelente", "malo"])
unique_elements, counts_elements = np.unique(survey_responses, return_counts=True)
counts = dict(zip(unique_elements, counts_elements))
print(counts)

{np.str_('bueno'): np.int64(4), np.str_('excelente'): np.int64(2), np.str_('malo'): np.int64(4)}


In [8]:
x = np.arange(10)
vista = x[1:3]

print(x)
print(vista)

# Modificar la vista
x[1:3] = [10, 11]
print(x)
print(vista)

# Crear una copia de la porción del array
copia = x[1:3].copy()

# Hacer cambios en el array original
x[1:3] = [12, 13]
print(x)
print(copia)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]
[ 0 12 13  3  4  5  6  7  8  9]
[10 11]
