In [2]:
import numpy as np 

In [9]:

# slicing
array = np.array([1,2,3,4,5,6,7])
print(array[1])
print(array[0])
print(array[1:4])
print(array[1:11])
print(array[-1:-11])
# indexacion booleana
bool_index = array >= 4
print(bool_index)
# acceder mediante indices
a_index = [2,4,0]
print(array[a_index])



#slicing con matrices
matriz = np.random.randint(1,11,size=(3,3))
print(matriz)
print(matriz[1,0])

print(matriz[:1,:2])


2
1
[2 3 4]
[2 3 4 5 6 7]
[]
[False False False  True  True  True  True]
[3 5 1]
[[ 3  8  9]
 [ 9 10  6]
 [ 7 10 10]]
9
[[3 8]]


In [ ]:
#broadcasting con numpy
prices = np.random.randint(100,300,(3,3))
discount = np.array([0.25])
discounted_prices = prices * discount
print(prices)
print(discounted_prices ) 

print(prices - discounted_prices) 

#operaciones logicas

print(np.all(prices > 0))
print(np.all(prices < 0))
print(np.all(prices < 500))
print(np.all(prices < 100))


#concatenacion


#matrices
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
B = np.array([[7, 8, 9]])             # Shape (1, 3)

C = np.concatenate((A, B), axis=0)  # Une por filas (verticalmente)
print(C) 

D = np.array([[10], [20]])  # Shape (2,1)

E = np.concatenate((A, D), axis=1)  # Une por columnas (horizontalmente)
print(E)

F = np.concatenate((A,B), axis=0)
print(F)
#vstaking

#np.concatenate((A, D), axis=1)

#✔ np.vstack((A, B)) → Une verticalmente (equivalente a axis=0).
#✔ np.hstack((A, B)) → Une horizontalmente (equivalente a axis=1).
#✔ np.dstack((A, B)) → Une en el tercer eje (útil para imágenes).
V = np.vstack((A, B))
H = np.hstack((A, D)) 
print('A:'+ A)
print('B:'+ B)
print('V:'+ V)
print('H:'+ H)

[[218 109 167]
 [283 265 257]
 [120 127 174]]
[[54.5  27.25 41.75]
 [70.75 66.25 64.25]
 [30.   31.75 43.5 ]]
[[163.5   81.75 125.25]
 [212.25 198.75 192.75]
 [ 90.    95.25 130.5 ]]
True
False
True
False
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 20]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U2'), dtype('int64')) -> None